-- RateQuip V12.2 Add-On 02 / Part 5
-- Delta migration; apply after 0023 and Part 4 migrations.
BEGIN;
CREATE SCHEMA IF NOT EXISTS rq_intelligence;
CREATE SCHEMA IF NOT EXISTS rq_ecosystem;
CREATE SCHEMA IF NOT EXISTS rq_marketplace_ext;
ALTER TABLE rq_intelligence.intelligence_analysis_run ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_analysis_run_tenant_policy ON rq_intelligence.intelligence_analysis_run;
CREATE POLICY intelligence_analysis_run_tenant_policy ON rq_intelligence.intelligence_analysis_run USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_document ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_document_tenant_policy ON rq_intelligence.intelligence_document;
CREATE POLICY intelligence_document_tenant_policy ON rq_intelligence.intelligence_document USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_document_version ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_document_version_tenant_policy ON rq_intelligence.intelligence_document_version;
CREATE POLICY intelligence_document_version_tenant_policy ON rq_intelligence.intelligence_document_version USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_document_clause ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_document_clause_tenant_policy ON rq_intelligence.intelligence_document_clause;
CREATE POLICY intelligence_document_clause_tenant_policy ON rq_intelligence.intelligence_document_clause USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_extracted_requirement ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_extracted_requirement_tenant_policy ON rq_intelligence.intelligence_extracted_requirement;
CREATE POLICY intelligence_extracted_requirement_tenant_policy ON rq_intelligence.intelligence_extracted_requirement USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_requirement_value ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_requirement_value_tenant_policy ON rq_intelligence.intelligence_requirement_value;
CREATE POLICY intelligence_requirement_value_tenant_policy ON rq_intelligence.intelligence_requirement_value USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_requirement_evidence ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_requirement_evidence_tenant_policy ON rq_intelligence.intelligence_requirement_evidence;
CREATE POLICY intelligence_requirement_evidence_tenant_policy ON rq_intelligence.intelligence_requirement_evidence USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_requirement_review ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_requirement_review_tenant_policy ON rq_intelligence.intelligence_requirement_review;
CREATE POLICY intelligence_requirement_review_tenant_policy ON rq_intelligence.intelligence_requirement_review USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_inference ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_inference_tenant_policy ON rq_intelligence.intelligence_inference;
CREATE POLICY intelligence_inference_tenant_policy ON rq_intelligence.intelligence_inference USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_gap ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_gap_tenant_policy ON rq_intelligence.intelligence_gap;
CREATE POLICY intelligence_gap_tenant_policy ON rq_intelligence.intelligence_gap USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_question ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_question_tenant_policy ON rq_intelligence.intelligence_question;
CREATE POLICY intelligence_question_tenant_policy ON rq_intelligence.intelligence_question USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_assumption ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_assumption_tenant_policy ON rq_intelligence.intelligence_assumption;
CREATE POLICY intelligence_assumption_tenant_policy ON rq_intelligence.intelligence_assumption USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_constraint ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_constraint_tenant_policy ON rq_intelligence.intelligence_constraint;
CREATE POLICY intelligence_constraint_tenant_policy ON rq_intelligence.intelligence_constraint USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_contradiction ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_contradiction_tenant_policy ON rq_intelligence.intelligence_contradiction;
CREATE POLICY intelligence_contradiction_tenant_policy ON rq_intelligence.intelligence_contradiction USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_risk ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_risk_tenant_policy ON rq_intelligence.intelligence_risk;
CREATE POLICY intelligence_risk_tenant_policy ON rq_intelligence.intelligence_risk USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_recommendation ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_recommendation_tenant_policy ON rq_intelligence.intelligence_recommendation;
CREATE POLICY intelligence_recommendation_tenant_policy ON rq_intelligence.intelligence_recommendation USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_recommendation_reason ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_recommendation_reason_tenant_policy ON rq_intelligence.intelligence_recommendation_reason;
CREATE POLICY intelligence_recommendation_reason_tenant_policy ON rq_intelligence.intelligence_recommendation_reason USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.supplier_response_analysis ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS supplier_response_analysis_tenant_policy ON rq_intelligence.supplier_response_analysis;
CREATE POLICY supplier_response_analysis_tenant_policy ON rq_intelligence.supplier_response_analysis USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.supplier_compliance_response ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS supplier_compliance_response_tenant_policy ON rq_intelligence.supplier_compliance_response;
CREATE POLICY supplier_compliance_response_tenant_policy ON rq_intelligence.supplier_compliance_response USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.supplier_deviation ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS supplier_deviation_tenant_policy ON rq_intelligence.supplier_deviation;
CREATE POLICY supplier_deviation_tenant_policy ON rq_intelligence.supplier_deviation USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.supplier_exclusion ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS supplier_exclusion_tenant_policy ON rq_intelligence.supplier_exclusion;
CREATE POLICY supplier_exclusion_tenant_policy ON rq_intelligence.supplier_exclusion USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_policy_version ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_policy_version_tenant_policy ON rq_intelligence.intelligence_policy_version;
CREATE POLICY intelligence_policy_version_tenant_policy ON rq_intelligence.intelligence_policy_version USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_user_feedback ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_user_feedback_tenant_policy ON rq_intelligence.intelligence_user_feedback;
CREATE POLICY intelligence_user_feedback_tenant_policy ON rq_intelligence.intelligence_user_feedback USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_intelligence.intelligence_confirmation ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS intelligence_confirmation_tenant_policy ON rq_intelligence.intelligence_confirmation;
CREATE POLICY intelligence_confirmation_tenant_policy ON rq_intelligence.intelligence_confirmation USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_ecosystem_node ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_ecosystem_node_tenant_policy ON rq_ecosystem.project_ecosystem_node;
CREATE POLICY project_ecosystem_node_tenant_policy ON rq_ecosystem.project_ecosystem_node USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_ecosystem_edge ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_ecosystem_edge_tenant_policy ON rq_ecosystem.project_ecosystem_edge;
CREATE POLICY project_ecosystem_edge_tenant_policy ON rq_ecosystem.project_ecosystem_edge USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_process_step ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_process_step_tenant_policy ON rq_ecosystem.project_process_step;
CREATE POLICY project_process_step_tenant_policy ON rq_ecosystem.project_process_step USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_work_package ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_work_package_tenant_policy ON rq_ecosystem.project_work_package;
CREATE POLICY project_work_package_tenant_policy ON rq_ecosystem.project_work_package USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_work_package_requirement ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_work_package_requirement_tenant_policy ON rq_ecosystem.project_work_package_requirement;
CREATE POLICY project_work_package_requirement_tenant_policy ON rq_ecosystem.project_work_package_requirement USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_work_package_supplier ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_work_package_supplier_tenant_policy ON rq_ecosystem.project_work_package_supplier;
CREATE POLICY project_work_package_supplier_tenant_policy ON rq_ecosystem.project_work_package_supplier USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_interface ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_interface_tenant_policy ON rq_ecosystem.project_interface;
CREATE POLICY project_interface_tenant_policy ON rq_ecosystem.project_interface USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_interface_party ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_interface_party_tenant_policy ON rq_ecosystem.project_interface_party;
CREATE POLICY project_interface_party_tenant_policy ON rq_ecosystem.project_interface_party USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_option ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_option_tenant_policy ON rq_ecosystem.project_option;
CREATE POLICY project_option_tenant_policy ON rq_ecosystem.project_option USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_option_component ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_option_component_tenant_policy ON rq_ecosystem.project_option_component;
CREATE POLICY project_option_component_tenant_policy ON rq_ecosystem.project_option_component USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_cost_estimate ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_cost_estimate_tenant_policy ON rq_ecosystem.project_cost_estimate;
CREATE POLICY project_cost_estimate_tenant_policy ON rq_ecosystem.project_cost_estimate USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_schedule_activity ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_schedule_activity_tenant_policy ON rq_ecosystem.project_schedule_activity;
CREATE POLICY project_schedule_activity_tenant_policy ON rq_ecosystem.project_schedule_activity USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_supplier_role ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_supplier_role_tenant_policy ON rq_ecosystem.project_supplier_role;
CREATE POLICY project_supplier_role_tenant_policy ON rq_ecosystem.project_supplier_role USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_ecosystem.project_completeness_score ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_completeness_score_tenant_policy ON rq_ecosystem.project_completeness_score;
CREATE POLICY project_completeness_score_tenant_policy ON rq_ecosystem.project_completeness_score USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_tenant_policy ON rq_marketplace_ext.operating_profile;
CREATE POLICY operating_profile_tenant_policy ON rq_marketplace_ext.operating_profile USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile_facility ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_facility_tenant_policy ON rq_marketplace_ext.operating_profile_facility;
CREATE POLICY operating_profile_facility_tenant_policy ON rq_marketplace_ext.operating_profile_facility USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile_process ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_process_tenant_policy ON rq_marketplace_ext.operating_profile_process;
CREATE POLICY operating_profile_process_tenant_policy ON rq_marketplace_ext.operating_profile_process USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile_equipment ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_equipment_tenant_policy ON rq_marketplace_ext.operating_profile_equipment;
CREATE POLICY operating_profile_equipment_tenant_policy ON rq_marketplace_ext.operating_profile_equipment USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile_material ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_material_tenant_policy ON rq_marketplace_ext.operating_profile_material;
CREATE POLICY operating_profile_material_tenant_policy ON rq_marketplace_ext.operating_profile_material USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile_packaging ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_packaging_tenant_policy ON rq_marketplace_ext.operating_profile_packaging;
CREATE POLICY operating_profile_packaging_tenant_policy ON rq_marketplace_ext.operating_profile_packaging USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile_cleaning_agent ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_cleaning_agent_tenant_policy ON rq_marketplace_ext.operating_profile_cleaning_agent;
CREATE POLICY operating_profile_cleaning_agent_tenant_policy ON rq_marketplace_ext.operating_profile_cleaning_agent USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.operating_profile_service_provider ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS operating_profile_service_provider_tenant_policy ON rq_marketplace_ext.operating_profile_service_provider;
CREATE POLICY operating_profile_service_provider_tenant_policy ON rq_marketplace_ext.operating_profile_service_provider USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.professional_profile ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS professional_profile_tenant_policy ON rq_marketplace_ext.professional_profile;
CREATE POLICY professional_profile_tenant_policy ON rq_marketplace_ext.professional_profile USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.professional_skill ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS professional_skill_tenant_policy ON rq_marketplace_ext.professional_skill;
CREATE POLICY professional_skill_tenant_policy ON rq_marketplace_ext.professional_skill USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.professional_availability ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS professional_availability_tenant_policy ON rq_marketplace_ext.professional_availability;
CREATE POLICY professional_availability_tenant_policy ON rq_marketplace_ext.professional_availability USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.job_opportunity ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS job_opportunity_tenant_policy ON rq_marketplace_ext.job_opportunity;
CREATE POLICY job_opportunity_tenant_policy ON rq_marketplace_ext.job_opportunity USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.project_opportunity ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_opportunity_tenant_policy ON rq_marketplace_ext.project_opportunity;
CREATE POLICY project_opportunity_tenant_policy ON rq_marketplace_ext.project_opportunity USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.laboratory_profile ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS laboratory_profile_tenant_policy ON rq_marketplace_ext.laboratory_profile;
CREATE POLICY laboratory_profile_tenant_policy ON rq_marketplace_ext.laboratory_profile USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.laboratory_test_method ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS laboratory_test_method_tenant_policy ON rq_marketplace_ext.laboratory_test_method;
CREATE POLICY laboratory_test_method_tenant_policy ON rq_marketplace_ext.laboratory_test_method USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.test_request ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS test_request_tenant_policy ON rq_marketplace_ext.test_request;
CREATE POLICY test_request_tenant_policy ON rq_marketplace_ext.test_request USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.sample ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sample_tenant_policy ON rq_marketplace_ext.sample;
CREATE POLICY sample_tenant_policy ON rq_marketplace_ext.sample USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.chain_of_custody_event ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS chain_of_custody_event_tenant_policy ON rq_marketplace_ext.chain_of_custody_event;
CREATE POLICY chain_of_custody_event_tenant_policy ON rq_marketplace_ext.chain_of_custody_event USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.freight_request_ext ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS freight_request_ext_tenant_policy ON rq_marketplace_ext.freight_request_ext;
CREATE POLICY freight_request_ext_tenant_policy ON rq_marketplace_ext.freight_request_ext USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.capacity_listing ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS capacity_listing_tenant_policy ON rq_marketplace_ext.capacity_listing;
CREATE POLICY capacity_listing_tenant_policy ON rq_marketplace_ext.capacity_listing USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.capacity_booking ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS capacity_booking_tenant_policy ON rq_marketplace_ext.capacity_booking;
CREATE POLICY capacity_booking_tenant_policy ON rq_marketplace_ext.capacity_booking USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.innovation_project ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS innovation_project_tenant_policy ON rq_marketplace_ext.innovation_project;
CREATE POLICY innovation_project_tenant_policy ON rq_marketplace_ext.innovation_project USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.project_team_role ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_team_role_tenant_policy ON rq_marketplace_ext.project_team_role;
CREATE POLICY project_team_role_tenant_policy ON rq_marketplace_ext.project_team_role USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.sourcing_preference ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sourcing_preference_tenant_policy ON rq_marketplace_ext.sourcing_preference;
CREATE POLICY sourcing_preference_tenant_policy ON rq_marketplace_ext.sourcing_preference USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.country_restriction ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS country_restriction_tenant_policy ON rq_marketplace_ext.country_restriction;
CREATE POLICY country_restriction_tenant_policy ON rq_marketplace_ext.country_restriction USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.commercial_referral ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS commercial_referral_tenant_policy ON rq_marketplace_ext.commercial_referral;
CREATE POLICY commercial_referral_tenant_policy ON rq_marketplace_ext.commercial_referral USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
ALTER TABLE rq_marketplace_ext.marketplace_fee_rule ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS marketplace_fee_rule_tenant_policy ON rq_marketplace_ext.marketplace_fee_rule;
CREATE POLICY marketplace_fee_rule_tenant_policy ON rq_marketplace_ext.marketplace_fee_rule USING (company_id = nullif(current_setting('app.company_id', true),'')::uuid) WITH CHECK (company_id = nullif(current_setting('app.company_id', true),'')::uuid);
COMMIT;
